# List of default reply files and subjects to be installed in the GLOBAL
# filespace

$files =
  {
   # English
   'en/ack_denial'              => ['Denied post to $LIST',                            'us-ascii', '7bit'],
   'en/ack_rejection'           => ['Rejection',                                       'us-ascii', '7bit'],
   'en/ack_stall'               => ['Stalled post to $LIST',                           'us-ascii', '7bit'],
   'en/ack_success'             => ['Success',                                         'us-ascii', '7bit'],
   'en/ack_timeout'             => ['Timeout',                                         'us-ascii', '7bit'],
   'en/digest_preindex'         => ['Index',                                           'us-ascii', '7bit'],
   'en/faq'                     => ['Default faq reply',                               'us-ascii', '7bit'],
   'en/file_sent'               => ['File has been sent',                              'us-ascii', '7bit'],
   'en/info'                    => ['Info',                                            'us-ascii', '7bit'],
   'en/intro'                   => ['Intro',                                           'us-ascii', '7bit'],
   'en/welcome'                 => ['Welcome',                                         'us-ascii', '7bit'],
   'en/registered'              => ['Welcome to $SITE',                                'us-ascii', '7bit'],
   'en/new_password'            => ['New password at $SITE',                           'us-ascii', '7bit'],
   'en/inform'                  => ['$UREQUEST $LIST',                                 'us-ascii', '7bit'],
   'en/repl_consult'            => ['Default consult mailreply file',                  'us-ascii', '7bit'],
   'en/repl_confirm'            => ['Default confirm mailreply file',                  'us-ascii', '7bit'],
   'en/repl_confcons'           => ['Default confirm+consult mailreply file',          'us-ascii', '7bit'],
   'en/repl_chain'              => ['Default chained mailreply file',                  'us-ascii', '7bit'],
   'en/repl_deny'               => ['Default denial replyfile',                        'us-ascii', '7bit'],
   'en/repl_forward'            => ['Default forward replyfile',                       'us-ascii', '7bit'],
   'en/request_response'        => ['Automated response from $REQUEST',                'us-ascii', '7bit'],
   'en/subscribe_to_self'       => ['Attempt to subscribe $LIST to itself',            'us-ascii', '7bit'],
   'en/token_reject'            => ['Rejected token $TOKEN',                           'us-ascii', '7bit'],
   'en/token_reject_owner'      => ['Token rejected by $REJECTER',                     'us-ascii', '7bit'],
   'en/token_remind'            => ['REMINDER from $LIST',                             'us-ascii', '7bit'],
   'en/help/help'               => ['Default help file',                               'us-ascii', '7bit'],
   'en/help/commands'           => ['Overview of available commands',                  'us-ascii', '7bit'],
   'en/help/parser'             => ['Information about the text parser',               'us-ascii', '7bit'],
   'en/help/patterns'           => ['Information about Majordomo patterns',            'us-ascii', '7bit'],
   'en/help/subscribe'          => ['Help on subscribing',                             'us-ascii', '7bit'],
   'en/help/topics'             => ['Available help topics',                           'us-ascii', '7bit'],
   'en/help/unknowntopic'       => ['Unknown topic',                                   'us-ascii', '7bit'],
   'en/help/admin'              => ['Available admin help topics',                     'us-ascii', '7bit'],
   'en/help/admin_commands'     => ['Overview of available administrative commands',   'us-ascii', '7bit'],
   'en/help/admin_configuration'=> ['Overview of configuration variables and methods', 'us-ascii', '7bit'],
   'en/help/admin_passwords'    => ['Information on Majordomo security and passwords', 'us-ascii', '7bit'],

   # Configuration variable descriptions
   'en/config/access_password_override'  => ['The access_password_override variable',  'us-ascii', '7bit'],
   'en/config/access_rules'              => ['The access_rules variable',              'us-ascii', '7bit'],
   'en/config/ack_attach_original'       => ['The ack_attach_original variable',       'us-ascii', '7bit'],
   'en/config/ack_denials_always'        => ['The ack_denials_always variable',        'us-ascii', '7bit'],
   'en/config/addr_allow_at_in_phrase'   => ['The addr_allow_at_in_phrase variable',   'us-ascii', '7bit'],
   'en/config/addr_allow_bang_paths'     => ['The addr_allow_bang_paths variable',     'us-ascii', '7bit'],
   'en/config/addr_allow_comments_after_route' => ['The addr_allow_comments_after_route variable', 'us-ascii', '7bit'],
   'en/config/addr_allow_ending_dot'     => ['The addr_allow_ending_dot variable',     'us-ascii', '7bit'],
   'en/config/addr_limit_length'         => ['The addr_limit_length variable',         'us-ascii', '7bit'],
   'en/config/addr_require_fqdn'         => ['The addr_require_fqdn variable',         'us-ascii', '7bit'],
   'en/config/addr_strict_domain_check'  => ['The addr_strict_domain_check variable',  'us-ascii', '7bit'],
   'en/config/addr_xforms'               => ['The addr_xforms variable',               'us-ascii', '7bit'],
   'en/config/admin_body'                => ['The admin_body variable',                'us-ascii', '7bit'],
   'en/config/admin_headers'             => ['The admin_headers variable',             'us-ascii', '7bit'],
   'en/config/administrivia'             => ['The administrivia variable',             'us-ascii', '7bit'],
   'en/config/advertise'                 => ['The advertise variable',                 'us-ascii', '7bit'],
   'en/config/advertise_subscribed'      => ['The advertise_subscribed variable',      'us-ascii', '7bit'],
   'en/config/allowed_classes'           => ['The allowed_classes variable',           'us-ascii', '7bit'],
   'en/config/allowed_flags'             => ['The allowed_flags variable',             'us-ascii', '7bit'],
   'en/config/archive_dir'               => ['The archive_dir variable',               'us-ascii', '7bit'],
   'en/config/archive_size'              => ['The archive_size variable',              'us-ascii', '7bit'],
   'en/config/archive_split'             => ['The archive_split variable',             'us-ascii', '7bit'],
   'en/config/attachment_rules'          => ['The attachment_rules variable',          'us-ascii', '7bit'],
   'en/config/bounce_probe_frequency'    => ['The bounce_probe_frequency variable',    'us-ascii', '7bit'],
   'en/config/category'                  => ['The category variable',                  'us-ascii', '7bit'],
   'en/config/chunksize'                 => ['The chunksize variable',                 'us-ascii', '7bit'],
   'en/config/comments'                  => ['The comments variable',                  'us-ascii', '7bit'],
   'en/config/confirm_url'               => ['The confirm_url variable',               'us-ascii', '7bit'],
   'en/config/database_backend'          => ['The database_backend variable',          'us-ascii', '7bit'],
   'en/config/date_info'                 => ['The date_info variable',                 'us-ascii', '7bit'],
   'en/config/date_intro'                => ['The date_intro variable',                'us-ascii', '7bit'],
   'en/config/debug'                     => ['The debug variable',                     'us-ascii', '7bit'],
   'en/config/default_class'             => ['The default_class variable',             'us-ascii', '7bit'],
   'en/config/default_flags'             => ['The default_flags variable',             'us-ascii', '7bit'],
   'en/config/default_language'          => ['The default_language variable',          'us-ascii', '7bit'],
   'en/config/default_lists_format'      => ['The default_lists_format variable',      'us-ascii', '7bit'],
   'en/config/delete_headers'            => ['The delete_headers variable',            'us-ascii', '7bit'],
   'en/config/delivery_rules'            => ['The delivery_rules variable',            'us-ascii', '7bit'],
   'en/config/description'               => ['The description variable',               'us-ascii', '7bit'],
   'en/config/description_long'          => ['The description_long variable',          'us-ascii', '7bit'],
   'en/config/description_max_lines'     => ['The description_max_lines variable',     'us-ascii', '7bit'],
   'en/config/digest_index_format'       => ['The digest_index_format variable',       'us-ascii', '7bit'],
   'en/config/digest_issues'             => ['The digest_issues variable',             'us-ascii', '7bit'],
   'en/config/digests'                   => ['The digests variable',                   'us-ascii', '7bit'],
   'en/config/dup_lifetime'              => ['The dup_lifetime variable',              'us-ascii', '7bit'],
   'en/config/faq_access'                => ['The faq_access variable',                'us-ascii', '7bit'],
   'en/config/file_search'               => ['The file_search variable',               'us-ascii', '7bit'],
   'en/config/file_share'                => ['The file_share variable',                'us-ascii', '7bit'],
   'en/config/filedir'                   => ['The filedir variable',                   'us-ascii', '7bit'],
   'en/config/get_access'                => ['The get_access variable',                'us-ascii', '7bit'],
   'en/config/index_access'              => ['The index_access variable',              'us-ascii', '7bit'],
   'en/config/info_access'               => ['The info_access variable',               'us-ascii', '7bit'],
   'en/config/inform'                    => ['The inform variable',                    'us-ascii', '7bit'],
   'en/config/intro_access'              => ['The intro_access variable',              'us-ascii', '7bit'],
   'en/config/master_password'           => ['The master_password variable',           'us-ascii', '7bit'],
   'en/config/max_header_line_length'    => ['The max_header_line_length variable',    'us-ascii', '7bit'],
   'en/config/max_in_core'               => ['The max_in_core variable',               'us-ascii', '7bit'],
   'en/config/max_mime_header_length'    => ['The max_mime_header_length variable',    'us-ascii', '7bit'],
   'en/config/max_total_header_length'   => ['The max_total_header_length variable',   'us-ascii', '7bit'],
   'en/config/maxlength'                 => ['The maxlength variable',                 'us-ascii', '7bit'],
   'en/config/message_footer'            => ['The message_footer variable',            'us-ascii', '7bit'],
   'en/config/message_footer_frequency'  => ['The message_footer_frequency variable',  'us-ascii', '7bit'],
   'en/config/message_fronter'           => ['The message_fronter variable',           'us-ascii', '7bit'],
   'en/config/message_fronter_frequency' => ['The message_fronter_frequency variable', 'us-ascii', '7bit'],
   'en/config/message_headers'           => ['The message_headers variable',           'us-ascii', '7bit'],
   'en/config/moderate'                  => ['The moderate variable',                  'us-ascii', '7bit'],
   'en/config/moderator'                 => ['The moderator variable',                 'us-ascii', '7bit'],
   'en/config/moderator_group'           => ['The moderator_group variable',           'us-ascii', '7bit'],
   'en/config/moderators'                => ['The moderators variable',                'us-ascii', '7bit'],
   'en/config/noadvertise'               => ['The noadvertise variable',               'us-ascii', '7bit'],
   'en/config/nonmember_flags'           => ['The nonmember_flags variable',           'us-ascii', '7bit'],
   'en/config/override_reply_to'         => ['The override_reply_to variable',         'us-ascii', '7bit'],
   'en/config/owners'                    => ['The owners variable',                    'us-ascii', '7bit'],
   'en/config/password_min_length'       => ['The password_min_length variable',       'us-ascii', '7bit'],
   'en/config/passwords'                 => ['The passwords variable',                 'us-ascii', '7bit'],
   'en/config/precedence'                => ['The precedence variable',                'us-ascii', '7bit'],
   'en/config/purge_received'            => ['The purge_received variable',            'us-ascii', '7bit'],
   'en/config/quote_pattern'             => ['The quote_pattern variable',             'us-ascii', '7bit'],
   'en/config/reply_to'                  => ['The reply_to variable',                  'us-ascii', '7bit'],
   'en/config/request_answer'            => ['The request_answer variable',            'us-ascii', '7bit'],
   'en/config/resend_host'               => ['The resend_host variable',               'us-ascii', '7bit'],
   'en/config/restrict_post'             => ['The restrict_post variable',             'us-ascii', '7bit'],
   'en/config/return_subject'            => ['The return_subject variable',            'us-ascii', '7bit'],
   'en/config/sender'                    => ['The sender variable',                    'us-ascii', '7bit'],
   'en/config/sequence_number'           => ['The sequence_number variable',           'us-ascii', '7bit'],
   'en/config/session_lifetime'          => ['The session_lifetime variable',          'us-ascii', '7bit'],
   'en/config/signature_separator'       => ['The signature_separator variable',       'us-ascii', '7bit'],
   'en/config/site_name'                 => ['The site_name variable',                 'us-ascii', '7bit'],
   'en/config/subject_prefix'            => ['The subject_prefix variable',            'us-ascii', '7bit'],
   'en/config/subscribe_policy'          => ['The subscribe_policy variable',          'us-ascii', '7bit'],
   'en/config/taboo_body'                => ['The taboo_body variable',                'us-ascii', '7bit'],
   'en/config/taboo_headers'             => ['The taboo_headers variable',             'us-ascii', '7bit'],
   'en/config/tmpdir'                    => ['The tmpdir variable',                    'us-ascii', '7bit'],
   'en/config/token_lifetime'            => ['The token_lifetime variable',            'us-ascii', '7bit'],
   'en/config/token_remind'              => ['The token_remind variable',              'us-ascii', '7bit'],
   'en/config/unsubscribe_policy'        => ['The unsubscribe_policy variable',        'us-ascii', '7bit'],
   'en/config/welcome'                   => ['The welcome variable',                   'us-ascii', '7bit'],
   'en/config/welcome_files'             => ['The welcome_files variable',             'us-ascii', '7bit'],
   'en/config/whereami'                  => ['The whereami variable',                  'us-ascii', '7bit'],
   'en/config/which_access'              => ['The which_access variable',              'us-ascii', '7bit'],
   'en/config/who_access'                => ['The who_access variable',                'us-ascii', '7bit'],
   'en/config/whoami'                    => ['The whoami variable',                    'us-ascii', '7bit'],
   'en/config/whoami_owner'              => ['The whoami_owner variable',              'us-ascii', '7bit'],
   


   # German
   'de/ack_denial'              => 'Denied post to $LIST',
   'de/ack_rejection'           => 'Rejection',
   'de/ack_stall'               => 'Stalled post to $LIST',
   'de/ack_success'             => 'Success',
   'de/ack_timeout'             => 'Timeout',
   'de/faq'                     => 'Default faq reply',
   'de/file_sent'               => 'File has been sent',
   'de/info'                    => 'Info',
   'de/intro'                   => 'Intro',
   'de/welcome'                 => 'Welcome',
#   'de/registered'              => 'Welcome to $SITE',
   'de/inform'                  => '$UREQUEST $LIST',
   'de/repl_consult'            => 'Default consult mailreply file',
   'de/repl_confirm'            => 'Default confirm mailreply file',
   'de/repl_confcons'           => 'Default confirm+consult mailreply file',
   'de/repl_chain'              => 'Default chained mailreply file',
   'de/repl_deny'               => 'Default denial replyfile',
   'de/repl_forward'            => 'Default forward replyfile',
#   'de/request_response'        => 'Automated response from $REQUEST',
   'de/subscribe_to_self'       => 'Attempt to subscribe $LIST to itself',
   'de/token_reject'            => 'Rejected token $TOKEN',
   'de/token_reject_owner'      => 'Token rejected by $REJECTER',
   'de/token_remind'            => 'REMINDER from $LIST',
#    'de/help/default'            => 'Default help file',
#    'de/help/commands'           => 'Overview of available commands',
#    'de/help/parser'             => 'Information about the text parser',
#    'de/help/subscribe'          => 'Help on subscribing',
#    'de/help/topics'             => 'Available help topics',
#    'de/help/admin_commands'     => 'Overview of available administrative commands',
#    'de/help/admin_configuration'=> 'Overview of configuration variables and methods',
#    'de/help/admin_passwords'    => 'Information on Majordomo security and passwords',

   # Informal German
   'de/informal/ack_denial'              => 'Denial',
   'de/informal/ack_rejection'           => 'Rejection',
   'de/informal/ack_stall'               => 'Stall',
   'de/informal/ack_success'             => 'Success',
   'de/informal/ack_timeout'             => 'Timeout',
   'de/informal/faq'                     => 'Default faq reply',
   'de/informal/file_sent'               => 'File has been sent',
   'de/informal/info'                    => 'Info',
   'de/informal/intro'                   => 'Intro',
   'de/informal/welcome'                 => 'Welcome',
#   'de/informal/registered'              => 'Welcome to $SITE',
   'de/informal/inform'                  => '$UREQUEST $LIST',
   'de/informal/repl_consult'            => 'Default consult mailreply file',
   'de/informal/repl_confirm'            => 'Default confirm mailreply file',
   'de/informal/repl_confcons'           => 'Default confirm+consult mailreply file',
   'de/informal/repl_chain'              => 'Default chained mailreply file',
   'de/informal/repl_deny'               => 'Default denial replyfile',
   'de/informal/repl_forward'            => 'Default forward replyfile',
#   'de/informal/request_response'        => 'Automated response from $REQUEST',
   'de/informal/subscribe_to_self'       => 'Attempt to subscribe $LIST to itself',
   'de/informal/token_reject'            => 'Rejected token $TOKEN',
   'de/informal/token_reject_owner'      => 'Token rejected by $REJECTER',
   'de/informal/token_remind'            => 'REMINDER from $LIST',
#    'de/informal/help/default'            => 'Default help file',
#    'de/informal/help/commands'           => 'Overview of available commands',
#    'de/informal/help/parser'             => 'Information about the text parser',
#    'de/informal/help/subscribe'          => 'Help on subscribing',
#    'de/informal/help/topics'             => 'Available help topics',
#    'de/informal/help/admin_commands'     => 'Overview of available administrative commands',
#    'de/informal/help/admin_configuration'=> 'Overview of configuration variables and methods',
#    'de/informal/help/admin_passwords'    => 'Information on Majordomo security and passwords',

  };

# Files that are conditional on a working web server
if ($indexflags & 1) {
  $files->{'en/confirm'} = ['CONFIRM from $LIST', 'us-ascii', '7bit'];
  $files->{'en/consult'} = ['CONSULT from $LIST', 'us-ascii', '7bit'];

  $files->{'de/confirm'} = 'CONFIRM from $LIST';
  $files->{'de/consult'} = 'CONSULT from $LIST';

  $files->{'de/informal/confirm'} = 'CONFIRM from $LIST';
  $files->{'de/informal/consult'} = 'CONSULT from $LIST';
}
else {
  $files->{'en/confirm'} = ['CONFIRM from $LIST', 'us-ascii', '7bit', 'en/confirm_noweb'];
  $files->{'en/consult'} = ['CONSULT from $LIST', 'us-ascii', '7bit', 'en/consult_noweb'];

  $files->{'de/confirm'} = ['CONFIRM from $LIST', 'ISO-8859-1', '8bit', 'de/confirm_noweb'];
  $files->{'de/consult'} = ['CONSULT from $LIST', 'ISO-8859-1', '8bit', 'de/consult_noweb'];

  $files->{'de/informal/confirm'} = ['CONFIRM from $LIST', 'ISO-8859-1', '8bit', 'de/informal/confirm_noweb'];
  $files->{'de/informal/consult'} = ['CONSULT from $LIST', 'ISO-8859-1', '8bit', 'de/informal/consult_noweb'];
}

# Directories; no longer useful but left here in case they are subsequently
# used, perhaps to fake a filespace to make the index command work better.
$dirs =
  ['stock'                  => 'Majordomo-supplied files',
   'stock/en'               => 'English',
   'stock/en/help'          => 'English Help files',
   'stock/de'               => 'German',
   'stock/de/help'          => 'German Help Files',
   'stock/de/informal'      => 'Informal German',
   'stock/de/informal/help' => 'Informal German Help Files',
  ];

[$files, $dirs];
